#+TITLE: Wire Cell Toolkit Python

* What's here.

This package provides Python modules in the ~wirecell~ namespace as well as
various ~wirecell-*~ command line programs.  These support the Wire Cell Toolkit
but do not depend on it.  If this package is available during the WCT build
process then some additonal unit tests can run using ~wirecell-*~ programs.

Some of the functionality provided includes converters and generators of major
WCT input data files including:

- field response functions
- wire geometry
- diagnostic plots

* Installation

It is recommended to use [[https://github.com/astral-sh/uv][uv]] for user and developer tasks.

** User

The package is not yet available in PyPI but the command line programs can be used like:

#+begin_example
uv run --with git+https://github.com/wirecell/wire-cell-python wirecell-util --help
#+end_example

** Developer

#+begin_example
git clone git@github.com:WireCell/wire-cell-python.git
cd wire-cell-python
uv sync
uv run wirecell-util --help
#+end_example


* Command line interfaces

Each main ~wirecell.<module>~ exposes most of its functionality via a
command line interface named ~wirecell-<module>~.  For example:

#+BEGIN_EXAMPLE
  $ wirecell-sigproc --help
  Usage: wirecell-sigproc [OPTIONS] COMMAND [ARGS]...

    Wire Cell Signal Processing Features

  Options:
    --help  Show this message and exit.

  Commands:
    convert-garfield              Convert an archive of a Garfield fileset...
    plot-garfield-track-response
#+END_EXAMPLE

If your shell supports it, see what commands are available with TAB
completion:

#+begin_example
  $ wirecell-<TAB><TAB>
#+end_example

* Documentation

In addition to the online ~-h/--help~ for main and sub commands, some
notes on specific commands are in [[file:docs/]].
