#+title: DNNROI support

* Input data

The full file set provide two subsets: "rec" giving reconstructed signal
information (final and some intermediate) and "tru" providing target ROI
classifications.

Input data is basic "frame file" schema in HDF5.  Paths like:

#+begin_example
/<EID>/<TYPE>_<TAG><N>
/100/{channels,frame,tickinfo}_{tag}0
#+end_example

EID is "event" identifier number.

Array types:

- ~channels~ 1D array of *electronic* (not image) channel ID numbers of rows of ~frame~.  
- ~frame~ 2D per-channel rows of waveform, eg shape (6000, 2488) for PDVD
- ~tickinfo~ trio of reference time, sample period and, starting tbin for the ~frame~.

Tags name the output of an intermediate or final signal process stage.  In "rec" files you may find these tags:
- ~break_roi_1st~
- ~break_roi_2nd~
- ~cleanup_roi~
- ~decon_charge~
- ~extend_roi~
- ~gauss~
- ~loose_lf~
- ~mp2_roi~
- ~mp3_roi~
- ~shrink_roi~
- ~tight_lf~
  
In "tru" files you may find these tags:
- ~ductor~

The final ~N~ marks the APA from which the data came.

* Data transforms

Both "rec" and "tru" share an initial transform:
- load arrays from file matching tags for given EID
- stack images along axis 2
- transpose images (chan,tick) to (tick,chan)


Every "rec" sample has additional processing:
- rebin across both image dimensions via ~mean()~
- normalize
- crop
- cyclic transpose to make first index the image channel.

Every "tru" sample has additional processing:
- squeeze out empty image channel index
- rebin as for "rec"
- crop as for "rec"
- threshold to set value 0 or 1.

* Network

The DNNROI network is examined and compared to U-Net.

** Dimensions 

The dimensions of output tensors from major units of the DNNROI network:
 

 | dir    | level | unit     |   ch | hpx | wpx |
 |--------+-------+----------+------+-----+-----|
 | in     |       | input    |    3 | 476 | 600 |
 | down   |     0 | dconv    |   64 | 476 | 600 |
 | down   |     0 | pool     |   64 | 238 | 300 |
 | down   |     1 | dconv    |  128 | 238 | 300 |
 | down   |     1 | pool     |  128 | 119 | 150 |
 | down   |     2 | dconv    |  256 | 119 | 150 |
 | down   |     2 | pool     |  256 |  59 |  75 |
 | down   |     3 | dconv    |  512 |  59 |  75 |
 | down   |     3 | pool     |  512 |  29 |  37 |
 | bottom |     4 | dconv    |  512 |  29 |  37 |
 | up     |     3 | upsample |  512 |  58 |  74 |
 | up     |     3 | pad      |  512 |  59 |  75 |
 | up     |     3 | cat      | 1024 |  59 |  75 |
 | up     |     3 | dconv    |  256 |  59 |  75 |
 | up     |     2 | upsample |  256 | 118 | 150 |
 | up     |     2 | pad      |  256 | 119 | 150 |
 | up     |     2 | cat      |  512 | 119 | 150 |
 | up     |     2 | dconv    |  128 | 119 | 150 |
 | up     |     1 | upsample |  128 | 238 | 300 |
 | up     |     1 | pad      |  128 | 238 | 300 |
 | up     |     1 | cat      |  256 | 238 | 300 |
 | up     |     1 | dconv    |   64 | 238 | 300 |
 | up     |     0 | upsample |   64 | 476 | 600 |
 | up     |     0 | pad      |   64 | 476 | 600 |
 | up     |     0 | cat      |  128 | 476 | 600 |
 | up     |     0 | dconv    |   64 | 476 | 600 |
 | out    |       | conv     |    1 | 476 | 600 |
 | out    |       | sigmoid  |    1 | 476 | 600 |
 

** Deviations from U-Net

The DNNROI network architecture takes inspiration from U-Net but deviates in many details from what is described in the U-Net paper.  In general, U-Net is more regular in image channel dimension while DNNROI is more regular in image pixel dimensions.  To achieve this and other goals, DNNROI inserts and swaps certain operations.  The following is a summary of the differences.

The main unit that makes up the "U" shape is the "double convolution" (dconv).
It is this general unit that is most modified in DNNROI from U-Net.  These
modifications vary depending on whether the dconv is in downward, bottom or
upward legs of the "U".

- DNNROI inserts a batch normalization between each pair of 2D convolution and ReLU.

- The U-net dconv reduces pixel dimension by 4 while DNNROI zero-pads after each
  2D convlution and the pixel dimension sizes remains unchanged.

- After the initial inflation to size 64, both U-Net and DNNROI dconv on the
  downward leg doubles the  channel dimension.  U-Net dconv on the "bottom"
  of the "U" also doubles this dimension while DNNROI does not.

- On the upward leg, U-Net dconv uniformly halves the channel dimension size.
  DNNROI quarters this dimension for the first three upward steps and halves it
  for the final step.

Changes in other units:

- DNNROI uses bilinear interpolated upsampling while U-Net uses ~ConvTranspose2d~.

- As a consequence, DNNROI zero-pads the pixel dimensions after upsampling when an odd target size is required.  The image size of 572 pixels used in the U-Net paper avoids encountering odd upsampling target sizes (relying on the 4 pixel loss in U-Net dconv). 

- DNNROI applies a final sigmoid to U-Net's output segmentation map.

- The U-Net skip transfers a core crop of the array whereas DNNROI preserves the entire array across the skip connection.  This is enabled by DNNROI applying padding in dconv units.  As a consequence, U-Net skip operation depends on the "natural" sizes of the upward U leg while DNNROI's upward U leg sizes depends on the "natural" sizes of the downward U leg.


* Performance

Test hyu's 10+10 VD HDF5 files on wcgpu0, (32 CPU core, RTX 4090).  Check
"typical" CPU and GPU utilization and memory usage via watching ~top~ and
~nvidia-smi~".  Time is wall clock.


| device | epochs | cache | CPU util | GPU util | CPU mem | GPU mem | time |
|--------+--------+-------+----------+----------+---------+---------+------|
| GPU    |      1 | false |     600% | 5%       | 1.7 GB  | 2.1 GB  | 42s  |
| GPU    |      4 | true  |    1000% | 80%      | 2.1 GB  | 2.1 GB  | 46s  |
| CPU    |      1 | false |    2200% | n/a      | 2.4 GB  | n/a     | 60s  |
| CPU    |      4 | true  |    3200% | n/a      | 3.0 GB  | n/a     | 180s |


Cache holds post transformed arrays is in CPU memory and only is reused with
more than one epoch.  When cache is on, the data is preloaded before training.


* Other things

light
